-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
return {
    diagnostics = {
        Error = ' ',
        Hint = ' ',
        Information = ' ',
        Question = ' ',
        Warning = ' ',
    },
    documents = {
        File = ' ',
        Files = ' ',
        Folder = ' ',
        FolderEmpty = ' ',
        OpenFolder = ' ',
        OpenFolderEmpty = ' ',
        SymLink = ' ',
        SymlinkFolder = ' ',
    },
    git = {
        Add = ' ',
        Branch = ' ',
        Diff = ' ',
        Ignore = '◌ ',
        Mod = ' ',
        Octoface = ' ',
        Remove = ' ',
        Rename = ' ',
        Repo = ' ',
        Tag = ' ',
        Untrack = ' ',
    },
    kind = {
        Class = ' ',
        Color = ' ',
        Constant = ' ',
        Constructor = ' ',
        Enum = ' ',
        EnumMember = ' ',
        Event = ' ',
        Field = ' ',
        File = ' ',
        Folder = ' ',
        Function = ' ',
        Interface = ' ',
        Keyword = ' ',
        Method = 'm ',
        Module = ' ',
        Operator = ' ',
        Property = ' ',
        Reference = ' ',
        Snippet = ' ',
        Struct = ' ',
        Text = ' ',
        TypeParameter = ' ',
        Unit = ' ',
        Value = ' ',
        Variable = ' ',
    },
    type = {
        Array = ' ',
        Boolean = '蘒 ',
        Number = ' ',
        Object = ' ',
        String = ' ',
    },
    ui = {
        Arrow = '➜ ',
        ArrowClosed = ' ',
        ArrowOpen = ' ',
        BigCircle = ' ',
        BigUnfilledCircle = ' ',
        Bookmark = ' ',
        Bug = ' ',
        Calendar = ' ',
        Check = ' ',
        ChevronRight = '',
        Circle = ' ',
        Close = ' ',
        CloudDownload = ' ',
        Code = ' ',
        Comment = ' ',
        Corner = '└ ',
        Dashboard = ' ',
        Database = ' ',
        Edge = '│ ',
        Fire = ' ',
        Firefox = ' ',
        Game = ' ',
        Gear = ' ',
        Heart = ' ',
        History = ' ',
        Incoming = ' ',
        List = '',
        Lock = ' ',
        Music = ' ',
        NewFile = ' ',
        None = '  ',
        Note = ' ',
        Outgoing = ' ',
        Package = ' ',
        Paint = ' ',
        Pencil = ' ',
        Power = '󰐥 ',
        Project = ' ',
        Rocket = ' ',
        Search = ' ',
        SignIn = ' ',
        SignOut = ' ',
        Table = ' ',
        Telescope = ' ',
        Test = ' ',
        Terminal = ' ',
        Trash = ' ',
        Time = ' ',
        Vim = ' ',
        Windows = ' ',
    },
}
