local which_key = require('which-key')
local icons = require('lib.icons')
local prompts = require('lib.prompts')

local setup = {
    preset = 'modern',
    plugins = {
        marks = true,
        registers = true,
        spelling = {
            enabled = true,
            suggestions = 30,
        },
        presets = {
            operators = true,
            motions = true,
            text_objects = true,
            windows = true,
            nav = true,
            z = true,
            g = true,
        },
    },
    icons = {
        breadcrumb = icons.ui.ArrowOpen,
        separator = icons.ui.Arrow,
        group = '',
        keys = {
            Space = icons.ui.Rocket,
        },
        rules = false, -- enable auto icon rules
    },
    win = {
        no_overlap = true,
        border = 'rounded',
        width = 0.5,
        height = { min = 5, max = 25 },
        padding = { 1, 2 },
        title = true,
        title_pos = 'center',
        zindex = 1000,
        wo = {
            winblend = 10,
        },
    },
    layout = {
        width = { min = 20 },
        spacing = 6,
        align = 'center',
    },
    show_help = false,
    show_keys = true,
    triggers = {
        { '<auto>', mode = 'nvisoct' },
        { '<leader>', mode = { 'n', 'v' } },
    },
}

local normal_mappings = {
    mode = 'n',
    { '<leader>x', ':x<cr>', desc = ' Save and Quit' },

    { '<leader>c', group = ' Code' },
    { '<leader>cF', ':retab<cr>', desc = 'Fix Tabs' },
    { '<leader>cR', ':ReloadConfig<cr>', desc = 'Reload Configs' },
    { '<leader>cc', ':ColorHighlighterToggle<cr>', desc = 'Highlight Colors' },
    { '<leader>cd', ':RootDir<cr>', desc = 'Root Directory' },
    { '<leader>ce', ':%Runner<cr>', desc = 'Execute File' },
    { '<leader>cl', '::g/^\\s*$/d<cr>', desc = 'Clean Empty Lines' },
    { '<leader>cm', ':MDPreview<cr>', desc = 'Markdown Preview' },
    { '<leader>cs', ':source %<cr>', desc = 'Source File' },

    { '<leader>e', group = ' Edit' },
    { '<leader>ea', ':b#<cr>', desc = 'Alternate File' },
    { '<leader>ec', group = 'Edit Configs' },
    { '<leader>eca', ':e ~/.config/shell/aliases.sh<cr>', desc = 'Shell Aliases' },
    { '<leader>ecA', ':e ~/.config/alacritty/alacritty.toml<cr>', desc = 'Alacritty Config' },
    { '<leader>ecb', ':e ~/.bashrc<cr>', desc = 'Bash Config' },
    { '<leader>ece', ':e ~/.config/shell/environment.sh<cr>', desc = 'Environment Config' },
    { '<leader>ecf', ':e ~/.config/shell/functions.sh<cr>', desc = 'Shell Functions' },
    { '<leader>ecg', ':e ~/.config/git/config<cr>', desc = 'Git Config' },
    { '<leader>eck', ':e ~/.config/kitty/kitty.conf<cr>', desc = 'Kitty Config' },
    { '<leader>ecl', ':e ~/.config/shell/local.sh<cr>', desc = 'Local Env' },
    { '<leader>ecn', ':e $MYVIMRC<cr>', desc = 'Neovim Init' },
    { '<leader>ecp', ':e ~/.config/nvim/lua/plugins/list.lua<cr>', desc = 'Plugin List' },
    { '<leader>ecq', ':e ~/.config/qutebrowser/config.py<cr>', desc = 'Qutebrowser Config' },
    { '<leader>ect', ':e ~/.config/tmux/tmux.conf<cr>', desc = 'Tmux Config' },
    { '<leader>ecv', ':e ~/.vimrc<cr>', desc = 'Vim Config' },
    { '<leader>ecz', ':e $ZDOTDIR/.zshrc<cr>', desc = 'Zsh Config' },
    { '<leader>ecZ', ':e $ZDOTDIR/prompt/init.zsh<cr>', desc = 'Zsh Prompt Config' },
    { '<leader>ee', ':lua Snacks.explorer()<cr>', desc = 'File Explorer' },
    { '<leader>em', ':e README.md<cr>', desc = 'Readme' },
    { '<leader>en', ':enew<cr>', desc = 'New File' },
    { '<leader>er', ':RangerPicker<cr>', desc = 'Ranger File Picker' },

    { '<leader>f', group = ' Find' },
    { '<leader>fx', ':%bd|e#|bd#<cr>', desc = 'Close except current' },
    { '<leader>fa', ':Seeker files<CR>', desc = 'Seeker files' },
    { '<leader>ff', ':Seeker git_files<CR>', desc = 'Seeker git_files' },
    { '<leader>fg', ':Seeker grep<CR>', desc = 'Seeker grep' },

    { '<leader>g', group = ' Git' },
    { '<leader>gA', ':Gitsigns stage_buffer<cr>', desc = 'Stage Buffer' },
    { '<leader>gC', ':CoAuthor<cr>', desc = 'Co-Authors' },
    { '<leader>gR', ':Gitsigns reset_buffer<cr>', desc = 'Reset Buffer' },
    { '<leader>ga', ':Gitsigns stage_hunk<cr>', desc = 'Stage Hunk' },
    { '<leader>gb', ":lua require('gitsigns').blame_line({full = true})<cr>", desc = 'Blame' },
    { '<leader>gc', ':STerm git commit<cr>', desc = 'Commit Staged' },
    { '<leader>gB', ":lua require('snacks').git.blame_line()<cr>", desc = 'Detailed Blame' },
    { '<leader>gd', ':Gitsigns diffthis HEAD<cr>', desc = 'Git Diff' },
    { '<leader>gg', ':lua require("snacks").lazygit()<cr>', desc = 'Lazygit' },
    { '<leader>gi', ':Gitsigns preview_hunk<cr>', desc = 'Hunk Info' },
    { '<leader>gj', ':Gitsigns next_hunk<cr>', desc = 'Next Hunk' },
    { '<leader>gk', ':Gitsigns prev_hunk<cr>', desc = 'Prev Hunk' },
    { '<leader>go', group = 'Octohub' },
    { '<leader>gr', ':Gitsigns reset_hunk<cr>', desc = 'Reset Hunk' },
    { '<leader>gt', group = 'Toggle' },
    { '<leader>gtb', ':Gitsigns toggle_current_line_blame<cr>', desc = 'Blame' },
    { '<leader>gtd', ':Gitsigns toggle_deleted<cr>', desc = 'Deleted' },
    { '<leader>gtl', ':Gitsigns toggle_linehl<cr>', desc = 'Line HL' },
    { '<leader>gtn', ':Gitsigns toggle_numhl<cr>', desc = 'Number HL' },
    { '<leader>gts', ':Gitsigns toggle_signs<cr>', desc = 'Signs' },
    { '<leader>gtw', ':Gitsigns toggle_word_diff<cr>', desc = 'Word Diff' },
    { '<leader>gu', ':Gitsigns undo_stage_hunk<cr>', desc = 'Undo Stage Hunk' },
    { '<leader>gv', ':Gitsigns select_hunk<cr>', desc = 'Select Hunk' },
    { '<leader>gw', ':lua require("snacks").gitbrowse()<cr>', desc = 'Git Browse' },

    { '<leader>i', group = ' Insert' },
    { '<leader>ia', group = ' AI Prompt' },
    { '<leader>iad', prompts.add_prompt('docs'), desc = 'Docs' },
    { '<leader>iae', prompts.add_prompt('explain'), desc = 'Explain' },
    { '<leader>iaf', prompts.add_prompt('fix'), desc = 'Fix' },
    { '<leader>iag', prompts.add_prompt('commit'), desc = 'Commit' },
    { '<leader>iao', prompts.add_prompt('optimize'), desc = 'Optimize' },
    { '<leader>iar', prompts.add_prompt('review'), desc = 'Review' },
    { '<leader>iat', prompts.add_prompt('tests'), desc = 'Tests' },
    { '<leader>id', ":put =strftime('## %a, %d %b, %Y, %r')<cr>", desc = 'Date' },
    { '<leader>if', ":put =expand('%:t')<cr>", desc = 'File Name' },
    { '<leader>ip', ':put %<cr>', desc = 'Relative Path' },
    { '<leader>iP', ':put %:p<cr>', desc = 'Absolute Path' },
    { '<leader>it', ":put =strftime('## %r')<cr>", desc = 'Time' },

    { '<leader>j', group = ' Jump' },
    { '<leader>jc', '*', desc = 'Word' },
    { '<leader>jh', '<C-o>', desc = 'Backward' },
    { '<leader>jl', '<C-i>', desc = 'Forward' },

    { '<leader>l', group = ' LSP' },
    { '<leader>la', ':lua vim.lsp.buf.code_action()<cr>', desc = 'Code Action' },
    { '<leader>lc', ':lua vim.lsp.buf.format({async = true})<cr>', desc = 'Code Format' },
    { '<leader>lh', ':lua vim.lsp.buf.hover()<cr>', desc = 'Hover Documentation' },
    { '<leader>lj', ':lua vim.diagnostic.jump({ count = 1 })<cr>', desc = 'Next Diagnostic' },
    { '<leader>lk', ':lua vim.diagnostic.jump({ count = -1 })<cr>', desc = 'Prev Diagnostic' },
    { '<leader>lr', ':lua vim.lsp.buf.rename()<cr>', desc = 'Rename' },

    { '<leader>m', group = ' Marks' },
    { '<leader>mg', group = 'Group Bookmarks' },
    { '<leader>mG', group = 'Group Bookmarks In Project' },
    { '<leader>mn', group = 'Next Bookmark In Group' },
    { '<leader>mp', group = 'Previous Bookmark In Group' },

    { '<leader>n', group = ' Notes' },
    { '<leader>na', ':lua Snacks.scratch.select()<cr>', desc = 'Select Scratch' },

    { '<leader>o', group = ' Options' },
    { '<leader>oi', 'vim.show_pos', desc = 'Inspect Position' },
    { '<leader>oN', ':lua Snacks.notifier.show_history()<cr>', desc = 'Notification History' },
    { '<leader>or', ':set relativenumber!<cr>', desc = 'Relative Numbers' },

    { '<leader>p', group = ' Packages' },
    { '<leader>pc', ':Lazy check<cr>', desc = 'Check' },
    { '<leader>pd', ':Lazy debug<cr>', desc = 'Debug' },
    { '<leader>pe', ':lua require("snacks").profiler.scratch()<cr>', desc = 'Profiler Scratch' },
    { '<leader>pf', ':lua require("snacks").profiler.pick()<cr>', desc = 'Profiler Pick' },
    { '<leader>pi', ':Lazy install<cr>', desc = 'Install' },
    { '<leader>pl', ':Lazy log<cr>', desc = 'Log' },
    { '<leader>pm', ':Mason<cr>', desc = 'Mason' },
    { '<leader>pp', ':Lazy<cr>', desc = 'Plugins' },
    { '<leader>pP', ':Lazy profile<cr>', desc = 'Profile' },
    { '<leader>pr', ':Lazy restore<cr>', desc = 'Restore' },
    { '<leader>ps', ':Lazy sync<cr>', desc = 'Sync' },
    { '<leader>pt', ':lua require("snacks").profiler.toggle()<cr>', desc = 'Profiler Toggle' },
    { '<leader>pu', ':Lazy update<cr>', desc = 'Update' },
    { '<leader>px', ':Lazy clean<cr>', desc = 'Clean' },

    { '<leader>q', group = ' Quit' },
    { '<leader>qa', ':qall<cr>', desc = 'Quit All' },
    { '<leader>qb', ':bw<cr>', desc = 'Close Buffer' },
    { '<leader>qd', ':lua require("snacks").bufdelete()<cr>', desc = 'Delete Buffer' },
    { '<leader>qf', ':qall!<cr>', desc = 'Force Quit' },
    { '<leader>qo', ':%bdelete|b#|bdelete#<cr>', desc = 'Close Others' },
    { '<leader>qq', ':q<cr>', desc = 'Quit' },
    { '<leader>qs', '<C-w>c', desc = 'Close Split' },
    { '<leader>qw', ':wq<cr>', desc = 'Write and Quit' },

    { '<leader>r', group = ' Refactor' },
    { '<leader>ra', ':Replace<cr>', desc = 'Replace All' },
    { '<leader>rb', ':%s///gc<Left><Left><Left><Left>', desc = 'Replace Buffer' },
    { '<leader>rd', '', desc = 'Go To Definition' }, -- treesitter navigation
    { '<leader>rh', '', desc = 'List Definition Head' },
    { '<leader>rj', '', desc = 'Next Usage' },
    { '<leader>rk', '', desc = 'Previous Usage' },
    { '<leader>rl', '', desc = 'List Definition' },
    { '<leader>rn', '', desc = 'Swap Next' },
    { '<leader>rp', '', desc = 'Swap Previous' },
    { '<leader>rr', '', desc = 'Smart Rename' },
    { '<leader>rs', ':%s/\\<<C-r><C-w>\\>/<C-r><C-w>/gI<Left><Left><Left>', desc = 'Replace Word Buffer' },
    { '<leader>rw', ':Replace <C-r><C-w><cr>', desc = 'Replace Word Everywhere' },

    { '<leader>s', group = ' Split' },
    { '<leader>s+', ':resize +10<cr>', desc = 'Increase window height' },
    { '<leader>s-', ':vertical resize -20<cr>', desc = 'Decrease window width' },
    { '<leader>s/', '<C-w>s', desc = 'Split Below' },
    { '<leader>s=', ':vertical resize +20<cr>', desc = 'Increase window width' },
    { '<leader>sH', ':vertical resize -10<cr>', desc = 'Decrease window width' },
    { '<leader>sJ', ':resize -5<cr>', desc = 'Decrease window height' },
    { '<leader>sK', ':resize +5<cr>', desc = 'Increase window height' },
    { '<leader>sL', ':vertical resize +10<cr>', desc = 'Increase window width' },
    { '<leader>s\\', '<C-w>v', desc = 'Split Right' },
    { '<leader>s_', ':resize -10<cr>', desc = 'Decrease window height' },
    { '<leader>s`', '<C-w>p', desc = 'Previous Window' },
    { '<leader>sa', ':split<cr>', desc = 'Horizontal Split' },
    { '<leader>sc', ':tabclose<cr>', desc = 'Close Tab' },
    { '<leader>sf', ':tabfirst<cr>', desc = 'First Tab' },
    { '<leader>sh', '<C-w>h', desc = 'Move Left' },
    { '<leader>sj', '<C-w>j', desc = 'Move Down' },
    { '<leader>sk', '<C-w>k', desc = 'Move Up' },
    { '<leader>sl', '<C-w>l', desc = 'Move Right' },
    { '<leader>sq', '<C-w>c', desc = 'Close Split' },
    { '<leader>ss', ':vsplit<cr>', desc = 'Vertical Split' },

    { '<leader>t', group = ' Terminal' },
    { '<leader>t`', ':Sterm<cr>', desc = 'Horizontal Terminal' },
    { '<leader>tc', ':Sterm bundle exec rails console<cr>', desc = 'Rails Console' },
    { '<leader>td', ':Sterm dexe<cr>', desc = 'Exe Launcher' },
    { '<leader>tn', ':Sterm node<cr>', desc = 'Node' },
    { '<leader>tp', ':Sterm bpython<cr>', desc = 'Python' },
    { '<leader>tr', ':Sterm irb<cr>', desc = 'Ruby' },
    { '<leader>ts', ':Sterm<cr>', desc = 'Horizontal Terminal' },
    { '<leader>tt', ':Fterm<cr>', desc = 'Terminal' },
    { '<leader>tv', ':Vterm<cr>', desc = 'Vertical Terminal' },
    { '<leader>tw', ':Sterm dexe --wait-before-exit<cr>', desc = 'Exe Launcher, Wait' },

    { '<leader>w', group = ' Writing' },
    { '<leader>wc', ':set spell!<cr>', desc = 'Spellcheck' },
    { '<leader>wd', ':lua require("snacks").dim.enable()<cr>', desc = 'Dim On' },
    { '<leader>wD', ':lua require("snacks").dim.disable()<cr>', desc = 'Dim Off' },
    { '<leader>wf', ":lua require'utils'.sudo_write()<cr>", desc = 'Force Write' },
    { '<leader>wj', ']s', desc = 'Next Misspell' },
    { '<leader>wk', '[s', desc = 'Prev Misspell' },
    { '<leader>wn', ':WriteNoFormat<cr>', desc = 'Write Without Formatting' },
    { '<leader>wq', ':wq<cr>', desc = 'Write and Quit' },
    { '<leader>ww', ':w<cr>', desc = 'Write' },
    { '<leader>wz', ':lua require("snacks").zen.zen()<cr>', desc = 'Zen' },
    { '<leader>wZ', ':lua require("snacks").zen.zoom()<cr>', desc = 'Zoom' },

    { '<leader>y', group = ' Yank' },
    { '<leader>yL', ':CopyAbsolutePathWithLine<cr>', desc = 'Absolute Path with Line' },
    { '<leader>yP', ':CopyAbsolutePath<cr>', desc = 'Absolute Path' },
    { '<leader>ya', ':%y+<cr>', desc = 'Copy Whole File' },
    { '<leader>yf', ':CopyFileName<cr>', desc = 'File Name' },
    { '<leader>yg', ':CopyGitUrl<cr>', desc = 'Copy Git URL' },
    { '<leader>yl', ':CopyRelativePathWithLine<cr>', desc = 'Relative Path with Line' },
    { '<leader>yp', ':CopyRelativePath<cr>', desc = 'Relative Path' },
}

-- Numerical mappings
for i = 1, 9 do
    table.insert(normal_mappings, {
        string.format('<leader>f%d', i),
        string.format(':LualineBuffersJump%d<cr>', i),
        desc = string.format('File %d', i),
    })
end

local visual_mappings = {
    mode = 'v',
    { '<leader>a', group = ' AI' },

    { '<leader>c', group = ' Code' },
    { '<leader>ce', "<esc>:'<,'>Runner<cr>", desc = 'Execute Selection' },
    { '<leader>cS', ':sort!<cr>', desc = 'Sort Desc' },
    { '<leader>ci', ':sort i<cr>', desc = 'Sort Case Insensitive' },
    { '<leader>cs', ':sort<cr>', desc = 'Sort Asc' },
    { '<leader>cu', ':!uniq<cr>', desc = 'Unique' },
    { '<leader>cx', ':lua<cr>', desc = 'Execute Lua' },

    { '<leader>g', group = ' Git' },
    { '<leader>ga', ":'<,'>Gitsigns stage_hunk<cr>", desc = 'Stage Hunk' },
    { '<leader>gr', ":'<,'>Gitsigns reset_hunk<cr>", desc = 'Reset Hunk' },
    { '<leader>gu', ":'<,'>Gitsigns undo_stage_hunk<cr>", desc = 'Undo Stage Hunk' },

    { '<leader>l', group = ' LSP' },
    { '<leader>la', ':lua vim.lsp.buf.code_action()<cr>', desc = 'Code Action' },

    { '<leader>y', group = ' Yank' },
    { '<leader>yg', ':CopyGitUrl<cr>', desc = 'Copy Git URL' },
}

local no_leader_mappings = {
    mode = 'n',
    { '<C-Down>', ':resize -10<cr>', desc = 'Decrease window height' },
    { '<C-Left>', ':vertical resize -10<cr>', desc = 'Decrease window width' },
    { '<C-Right>', ':vertical resize +10<cr>', desc = 'Increase window width' },
    { '<C-Up>', ':resize +10<cr>', desc = 'Increase window height' },
    { '<C-g>', ':Fterm lazygit<cr>', desc = 'Lazygit' },

    { '[', group = ' Previous' },
    { '[g', ':Gitsigns prev_hunk<cr>', desc = 'Git Hunk' },
    { '[o', group = 'Textobjects' },

    { ']', group = ' Next' },
    { ']g', ':Gitsigns next_hunk<cr>', desc = 'Git Hunk' },
    { ']o', group = 'Textobjects' },

    { 'gd', ':lua Snacks.picker.lsp_definitions()<cr>', desc = 'Goto Definition' },
    { 'H', ':bprevious<cr>', desc = 'Previous Buffer' },
    { 'K', ':lua vim.lsp.buf.hover()<cr>', desc = 'LSP Hover' },
    { 'L', ':bnext<cr>', desc = 'Next Buffer' },
    { 'Q', ':qall!<cr>', desc = 'Force Quit!' },
    { 'U', ':redo<cr>', desc = 'Redo' },
}

which_key.setup(setup)
which_key.add(normal_mappings)
which_key.add(visual_mappings)
which_key.add(no_leader_mappings)

local user_keybindings = require('lib.util').get_user_config('user_keybindings', {})
which_key.add(user_keybindings)
